"""Esquema inicial completo de Platform Core (migraciones consolidadas).

Única migración del esquema: crea todas las tablas del metadata actual y siembra
las dos filas singleton que los servicios exigen (``system_settings`` con la
política por defecto y ``backup_settings`` con respaldos apagados y Drive
desconectado). La tabla del broker de Taskiq NO se migra: la crea el broker.

Historial previo consolidado el 2026-07-14 (ver decisions.md): las instalaciones
anteriores a esta fecha deben recrearse desde cero.

Revision ID: 47047ac47de1
Revises:
Create Date: 2026-07-14
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47047ac47de1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Extensiones del motor de consultas: ``unaccent`` (búsqueda insensible a acentos) y
    # ``pg_trgm`` (búsqueda difusa por trigramas). Son extensiones "trusted" (PG13+): un
    # usuario con CREATE en la base puede instalarlas sin superusuario. Idempotente.
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'retrying', 'succeeded', 'failed', 'skipped', 'pruned', name='backup_run_status', native_enum=False, create_constraint=True), server_default='queued', nullable=False, comment='Estado: queued, running, retrying, succeeded, failed, skipped o pruned.'),
    sa.Column('trigger_kind', sa.Enum('scheduled', 'manual', name='backup_trigger_kind', native_enum=False, create_constraint=True), nullable=False, comment='Origen de la ejecución: scheduled (horario diario) o manual.'),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True, comment='Ventana programada (UTC) que originó la ejecución, si fue scheduled.'),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True, comment='Momento (UTC) a partir del cual la ejecución puede reclamarse (cola y reintentos).'),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False, comment='Intentos realizados (máximo BACKUP_MAX_ATTEMPTS).'),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True, comment='Vencimiento (UTC) del lease del worker; al expirar, la ejecución es recuperable.'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='Inicio (UTC) del primer intento.'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='Fin (UTC) del intento que dejó la ejecución en estado terminal.'),
    sa.Column('file_name', sa.String(length=160), nullable=True, comment='Nombre final del archivo cifrado subido ({prefix}-{timestampUTC}-{runId}.tar.age).'),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True, comment='Tamaño del archivo cifrado subido, en bytes.'),
    sa.Column('ciphertext_sha256', sa.String(length=64), nullable=True, comment='SHA-256 (hex) del archivo cifrado (verificación e idempotencia de subida).'),
    sa.Column('drive_file_id', sa.String(length=128), nullable=True, comment='Id del archivo en Google Drive.'),
    sa.Column('drive_folder_id', sa.String(length=128), nullable=True, comment='Carpeta de Drive donde quedó el archivo.'),
    sa.Column('encryption_fingerprint', sa.String(length=64), nullable=True, comment='Huella del recipient de age usado para cifrar este respaldo.'),
    sa.Column('retention_roles', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False, comment='Roles de retención del respaldo: daily, monthly y/o yearly.'),
    sa.Column('error_code', sa.String(length=96), nullable=True, comment='Código del último error de la ejecución (clasificado, sin texto crudo).'),
    sa.Column('error_summary', sa.String(length=255), nullable=True, comment='Resumen SEGURO del último error (sin tokens, rutas ni datos clínicos).'),
    sa.Column('pruned_at', sa.DateTime(), nullable=True, comment='Momento (UTC) en que la retención borró el archivo remoto (la fila se conserva).'),
    sa.Column('explorer_status', sa.Enum('not_requested', 'building', 'ready', 'failed', name='backup_explorer_status', native_enum=False, create_constraint=True), nullable=True, comment='Estado del artefacto de exploración: not_requested, building, ready o failed.'),
    sa.Column('explorer_file_name', sa.String(length=255), nullable=True, comment='Nombre del SQLite de exploración subido ({prefix}-{ts}-{run}.explorer.sqlite[.age]).'),
    sa.Column('explorer_file_size_bytes', sa.BigInteger(), nullable=True, comment='Tamaño del artefacto de exploración subido, en bytes.'),
    sa.Column('explorer_ciphertext_sha256', sa.String(length=64), nullable=True, comment='SHA-256 (hex) del artefacto de exploración subido.'),
    sa.Column('explorer_drive_file_id', sa.String(length=128), nullable=True, comment='Id del artefacto de exploración en Google Drive.'),
    sa.Column('explorer_policy_version', sa.Integer(), nullable=True, comment='Versión de la política de exportación con la que se construyó el explorer.'),
    sa.Column('explorer_created_at', sa.DateTime(), nullable=True, comment='Momento (UTC) en que el artefacto de exploración quedó listo.'),
    sa.Column('explorer_error_code', sa.String(length=96), nullable=True, comment='Código del error del explorer (clasificado, sin texto crudo).'),
    sa.Column('explorer_error_summary', sa.String(length=255), nullable=True, comment='Resumen SEGURO del error del explorer (sin datos clínicos ni secretos).'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación de la ejecución.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última actualización.'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_runs'))
    )
    op.create_index('ix_backup_runs_drive_file', 'backup_runs', ['drive_file_id'], unique=False)
    op.create_index('ix_backup_runs_status_finished', 'backup_runs', ['status', 'finished_at'], unique=False)
    op.create_index('ix_backup_runs_status_next_attempt', 'backup_runs', ['status', 'next_attempt_at'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Desactivación lógica: false elimina al usuario sin borrar el registro.'),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=True, comment='Token de versión del usuario. Cambia al modificar contraseña, email o al forzar cierre de sesiones activas.'),
    sa.Column('locked_until', sa.DateTime(), nullable=True, comment='Fecha hasta la cual la cuenta está bloqueada por intentos fallidos de login.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación del registro.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última modificación.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que realizó la última modificación.'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_user_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('web_push_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_key', sa.String(length=255), nullable=False),
    sa.Column('private_key_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web_push_credentials'))
    )
    op.create_table('ai_provider_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Usuario dueño de la credencial.'),
    sa.Column('provider', sa.Enum('openai', 'anthropic', 'gemini', 'openrouter', 'ollama', name='ai_provider', native_enum=False, create_constraint=True), nullable=False, comment='Proveedor de IA de la credencial.'),
    sa.Column('credential_type', sa.Enum('api_key', 'oauth', name='ai_credential_type', native_enum=False, create_constraint=True), server_default='api_key', nullable=False, comment='Tipo de credencial: api_key (secreto estático) u oauth (perfil cifrado).'),
    sa.Column('label', sa.String(length=120), nullable=False, comment='Etiqueta legible elegida por el usuario para identificar la credencial.'),
    sa.Column('secret_encrypted', sa.Text(), nullable=False, comment='Secreto del proveedor cifrado con Fernet (NUNCA el claro).'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Si la credencial está habilitada para usarse.'),
    sa.Column('default_model', sa.String(length=160), nullable=True, comment='Modelo por defecto sugerido para esta credencial.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación de la credencial.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Usuario que creó la credencial.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Última actualización de la credencial.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que modificó la credencial.'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Fecha de eliminación lógica de la credencial.'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='Usuario que eliminó lógicamente la credencial.'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_ai_provider_credentials_created_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], name=op.f('fk_ai_provider_credentials_deleted_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_ai_provider_credentials_updated_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_ai_provider_credentials_user_id_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_provider_credentials'))
    )
    op.create_index('ix_ai_provider_credentials_provider', 'ai_provider_credentials', ['provider'], unique=False)
    op.create_index('ix_ai_provider_credentials_user', 'ai_provider_credentials', ['user_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=False, comment='Tabla o tipo de entidad afectada por el evento.'),
    sa.Column('entity_id', sa.UUID(), nullable=False, comment='Identificador del registro afectado.'),
    sa.Column('action', sa.String(length=120), nullable=False, comment='Acción realizada, por ejemplo system_settings_updated o backup_drive_connected.'),
    sa.Column('actor_user_id', sa.UUID(), nullable=True, comment='Usuario que ejecutó la acción. Puede ser nulo para procesos automáticos del sistema.'),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True, comment='Resumen de los campos modificados.'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Motivo del evento, cuando aplique.'),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora del evento de auditoría.'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], name=op.f('fk_audit_events_actor_user_id_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_action', 'audit_events', ['action'], unique=False)
    op.create_index('ix_audit_events_actor_user', 'audit_events', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_events_occurred_at', 'audit_events', ['occurred_at'], unique=False)
    op.create_table('backup_oauth_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Administrador que inició la conexión de Drive.'),
    sa.Column('state_hash', sa.String(length=64), nullable=False, comment='SHA-256 (hex) del state OAuth; nunca se guarda el valor original.'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='Expiración del state (UTC): 10 minutos desde su creación.'),
    sa.Column('consumed_at', sa.DateTime(), nullable=True, comment='Momento (UTC) en que el callback consumió el state (una sola vez).'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación del state.'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_backup_oauth_states_user_id_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_oauth_states')),
    sa.UniqueConstraint('state_hash', name=op.f('uq_backup_oauth_states_state_hash'))
    )
    op.create_table('backup_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('singleton_key', sa.Boolean(), server_default='true', nullable=False, comment='Siempre true: garantiza una sola fila de configuración.'),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False, comment='Respaldos diarios habilitados (requiere Drive activo y cifrado configurado).'),
    sa.Column('timezone', sa.String(length=64), nullable=False, comment='Zona horaria IANA en la que se interpreta la hora diaria (p. ej. America/Monterrey).'),
    sa.Column('daily_time', sa.Time(), nullable=False, comment='Hora local del respaldo diario (en la zona configurada).'),
    sa.Column('next_run_at', sa.DateTime(), nullable=True, comment='Próxima ejecución programada, en UTC (la calcula el backend, no el usuario).'),
    sa.Column('filename_prefix', sa.String(length=48), nullable=False, comment='Prefijo del nombre de archivo del respaldo (letras/números/_/-).'),
    sa.Column('retention_daily_count', sa.Integer(), nullable=False, comment='Copias diarias a conservar en Drive (0-365).'),
    sa.Column('retention_monthly_count', sa.Integer(), nullable=False, comment='Copias mensuales a conservar en Drive (0-120).'),
    sa.Column('retention_yearly_count', sa.Integer(), nullable=False, comment='Copias anuales a conservar en Drive (0-50).'),
    sa.Column('run_lease_minutes', sa.Integer(), nullable=True, comment='Minutos del lease de una ejecución RUNNING antes de considerarla huérfana y recuperarla. NULL = default del despliegue (BACKUP_RUN_LEASE_MINUTES).'),
    sa.Column('max_attempts', sa.Integer(), nullable=True, comment='Intentos máximos de una ejecución antes de marcarla fallida. NULL = default del despliegue (BACKUP_MAX_ATTEMPTS).'),
    sa.Column('age_recipient', sa.Text(), nullable=True, comment='Recipient PÚBLICO de age con el que se cifra el archivo (la clave privada vive fuera del sistema).'),
    sa.Column('age_recipient_fingerprint', sa.String(length=64), nullable=True, comment='Huella (sha256 truncado) del recipient configurado, para mostrar y auditar.'),
    sa.Column('age_identity_ciphertext', sa.Text(), nullable=True, comment='Identidad PRIVADA de age CIFRADA (Fernet), sólo si el par lo generó el sistema. Nunca se proyecta a la API; se reenvía por correo al administrador.'),
    sa.Column('google_drive_client_id', sa.String(length=255), nullable=True, comment='Client ID del OAuth de Google (capturado en la UI; única fuente: esta fila).'),
    sa.Column('google_drive_client_secret_ciphertext', sa.Text(), nullable=True, comment='Client secret del OAuth de Google CIFRADO (Fernet). Nunca se proyecta a la API.'),
    sa.Column('explorer_enabled', sa.Boolean(), nullable=False, comment='Genera el artefacto de exploración (SQLite legible) junto a cada respaldo.'),
    sa.Column('drive_status', sa.Enum('disconnected', 'active', 'needs_reauth', name='backup_drive_status', native_enum=False, create_constraint=True), server_default='disconnected', nullable=False, comment='Estado de la conexión con Google Drive: disconnected, active o needs_reauth.'),
    sa.Column('drive_refresh_token_ciphertext', sa.Text(), nullable=True, comment='Refresh token de Google CIFRADO (Fernet). Nunca se proyecta a la API.'),
    sa.Column('drive_folder_id', sa.String(length=128), nullable=True, comment='Carpeta de Drive creada por la app donde se suben los respaldos.'),
    sa.Column('drive_connected_at', sa.DateTime(), nullable=True, comment='Fecha y hora (UTC) de la última conexión de Drive.'),
    sa.Column('last_error_code', sa.String(length=96), nullable=True, comment='Código del último error visible al administrador (alerta persistente).'),
    sa.Column('last_error_summary', sa.String(length=255), nullable=True, comment='Resumen SEGURO del último error (sin tokens, rutas ni datos clínicos).'),
    sa.Column('last_error_at', sa.DateTime(), nullable=True, comment='Fecha y hora (UTC) del último error registrado.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación de la configuración.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última edición.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que actualizó la configuración.'),
    sa.CheckConstraint('retention_daily_count >= 0 AND retention_daily_count <= 365', name=op.f('ck_backup_settings_backup_settings_retention_daily_range')),
    sa.CheckConstraint('retention_monthly_count >= 0 AND retention_monthly_count <= 120', name=op.f('ck_backup_settings_backup_settings_retention_monthly_range')),
    sa.CheckConstraint('retention_yearly_count >= 0 AND retention_yearly_count <= 50', name=op.f('ck_backup_settings_backup_settings_retention_yearly_range')),
    sa.CheckConstraint('singleton_key = true', name=op.f('ck_backup_settings_backup_settings_singleton')),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_backup_settings_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_settings')),
    sa.UniqueConstraint('singleton_key', name=op.f('uq_backup_settings_singleton_key'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_status', sa.String(length=10), nullable=False),
    sa.Column('email_error', sa.String(length=200), nullable=True),
    sa.Column('push_status', sa.String(length=10), nullable=False),
    sa.Column('push_error', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("email_status IN ('pending', 'sent', 'failed', 'skipped')", name=op.f('ck_notifications_notifications_email_status')),
    sa.CheckConstraint("kind IN ('system', 'promo')", name=op.f('ck_notifications_notifications_kind')),
    sa.CheckConstraint("push_status IN ('pending', 'sent', 'failed', 'skipped')", name=op.f('ck_notifications_notifications_push_status')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notifications_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_email_pending', 'notifications', ['email_status', 'created_at'], unique=False)
    op.create_index('ix_notifications_push_pending', 'notifications', ['push_status', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_push_subscriptions_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_subscriptions')),
    sa.UniqueConstraint('endpoint', name=op.f('uq_push_subscriptions_endpoint'))
    )
    op.create_index('ix_push_subscriptions_user', 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True, comment='Descripción legible del propósito del rol.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación del registro.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última modificación.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que realizó la última modificación.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Desactivación lógica: false inhabilita el rol y sus permisos asociados sin borrar el registro.'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_role_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('name', name=op.f('uq_role_name'))
    )
    op.create_table('system_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('singleton_key', sa.Boolean(), nullable=False, comment='Siempre true: fuerza una sola fila de configuración del sistema.'),
    sa.Column('public_registration_enabled', sa.Boolean(), nullable=False, comment='Política de registro público (auto-registro por correo). Única fuente de verdad: no existe gate de entorno.'),
    sa.Column('app_base_url', sa.String(length=255), nullable=True, comment='Dominio público de la instalación (https://…): base de los enlaces absolutos de correo y de los redirect URIs de OAuth.'),
    sa.Column('app_base_url_verified_at', sa.DateTime(), nullable=True, comment='Momento (UTC) en que el dominio base se verificó; lo escribe el backend.'),
    sa.Column('institution_name', sa.String(length=200), nullable=True, comment='Nombre de la institución (membrete y encabezados).'),
    sa.Column('login_verification_mode', sa.String(length=10), nullable=False, comment='Segundo paso de login verificado por correo: disabled, code (código de un solo uso) o link (enlace). Los usuarios con cobertura administrativa completa quedan exentos SIEMPRE (garantía anti-bloqueo); los clientes Bearer no re-verifican.'),
    sa.Column('password_reset_enabled', sa.Boolean(), nullable=False, comment='Recuperación de contraseña por correo. Sin candado de despliegue (bajo riesgo); apagarla con registro cerrado y un solo admin puede dejar la instalación sin acceso (salida: seed CLI).'),
    sa.Column('analytics_enabled', sa.Boolean(), nullable=False, comment='Google Analytics 4 en el sitio público (storefront + login/registro). Apagado no se carga ningún script ni se envía evento alguno. El panel y el admin NUNCA se miden.'),
    sa.Column('analytics_ga4_measurement_id', sa.String(length=30), nullable=True, comment='ID de medición de GA4 (G-XXXXXXXXXX). Es un identificador público por diseño de Google; aquí no se guarda ningún secreto de analítica.'),
    sa.Column('analytics_require_consent', sa.Boolean(), nullable=False, comment='Exigir consentimiento de cookies analíticas: hasta que el visitante acepte, no se carga el script ni se envía ningún evento.'),
    sa.Column('analytics_debug_mode', sa.Boolean(), nullable=False, comment='Enviar los eventos con debug_mode para validarlos en GA4 DebugView. Solo para pruebas; apagar en operación normal.'),
    sa.Column('login_attempts_before_lock', sa.Integer(), nullable=True, comment='Intentos fallidos de login antes de bloquear la cuenta. NULL = usar el default del despliegue (TRYS_BEFORE_LOCK).'),
    sa.Column('email_token_minutes', sa.Integer(), nullable=True, comment='Minutos de vigencia de los tokens enviados por correo (registro, recuperación, verificación de login). NULL = usar el default del despliegue (EMAIL_TOKEN_EXPIRE_MINUTES).'),
    sa.Column('audit_retention_days', sa.Integer(), nullable=True, comment='Días a conservar en la bitácora de auditoría; la poda diaria elimina lo más antiguo. NULL = sin poda (crecimiento sin límite).'),
    sa.Column('notification_retention_days', sa.Integer(), nullable=True, comment='Días a conservar las notificaciones LEÍDAS; la poda diaria elimina las leídas más antiguas (las no leídas nunca se podan). NULL = sin poda.'),
    sa.Column('application_timezone', sa.String(length=64), nullable=True, comment='Zona horaria IANA de la instalación (p. ej. America/Monterrey): define los límites de día de los filtros de calendario. NULL = default del despliegue (APPLICATION_TIMEZONE). El cambio aplica en segundos (caché corto por proceso).'),
    sa.Column('agent_ticket_ttl_seconds', sa.Integer(), nullable=True, comment='Segundos de vigencia del ticket de conexión al Agent Gateway. NULL = default del despliegue (AGENT_GATEWAY_TICKET_TTL_SECONDS).'),
    sa.Column('agent_lease_ttl_seconds', sa.Integer(), nullable=True, comment='Segundos de vigencia del arriendo de credencial de proveedor de IA por turno. NULL = default del despliegue (AGENT_GATEWAY_LEASE_TTL_SECONDS).'),
    sa.Column('brand_logo_content', sa.LargeBinary(), nullable=True, comment='Logo de la instalación (binario raster verificado). NULL = sin logo.'),
    sa.Column('brand_logo_mime', sa.String(length=100), nullable=True, comment='Content-type del logo (image/png, image/jpeg, image/webp).'),
    sa.Column('brand_logo_updated_at', sa.DateTime(), nullable=True, comment='Última actualización del logo (cache-buster del manifest).'),
    sa.Column('google_login_enabled', sa.Boolean(), nullable=False, comment="Botón 'Continuar con Google' en el login. Vincula cuentas por correo VERIFICADO de Google; el alta de cuentas nuevas exige además el registro público efectivo (mismo doble candado que el registro)."),
    sa.Column('google_auth_client_id', sa.String(length=255), nullable=True, comment='Client ID del OAuth de Google para el LOGIN (distinto del de respaldos).'),
    sa.Column('google_auth_client_secret_ciphertext', sa.Text(), nullable=True, comment='Client secret del OAuth de login CIFRADO (Fernet). Nunca se proyecta a la API.'),
    sa.Column('email_mode', sa.String(length=20), nullable=False, comment='Transporte de correo: environment (SMTP_* del entorno; Mailpit en dev), smtp (credenciales de esta fila) o resend (API key de esta fila).'),
    sa.Column('email_from_address', sa.String(length=255), nullable=True, comment='Remitente para los modos smtp/resend (environment usa SMTP_FROM_*).'),
    sa.Column('email_from_name', sa.String(length=120), nullable=True, comment='Nombre visible del remitente (modos smtp/resend).'),
    sa.Column('email_smtp_host', sa.String(length=255), nullable=True, comment='Servidor SMTP (modo smtp).'),
    sa.Column('email_smtp_port', sa.Integer(), nullable=True, comment='Puerto SMTP (modo smtp).'),
    sa.Column('email_smtp_username', sa.String(length=255), nullable=True, comment='Usuario SMTP (modo smtp).'),
    sa.Column('email_smtp_password_ciphertext', sa.Text(), nullable=True, comment='Contraseña SMTP CIFRADA (Fernet). Nunca se proyecta a la API.'),
    sa.Column('email_smtp_tls', sa.Boolean(), nullable=False, comment='STARTTLS (modo smtp).'),
    sa.Column('email_smtp_ssl', sa.Boolean(), nullable=False, comment='SSL/TLS directo (modo smtp).'),
    sa.Column('email_resend_api_key_ciphertext', sa.Text(), nullable=True, comment='API key de Resend CIFRADA (Fernet). Nunca se proyecta a la API.'),
    sa.Column('email_last_test_at', sa.DateTime(), nullable=True, comment='Momento (UTC) del último correo de prueba; lo escribe la acción de test.'),
    sa.Column('email_last_test_status', sa.String(length=20), nullable=True, comment='Resultado del último test: ok o failed (estado derivado, no editable).'),
    sa.Column('email_last_test_error', sa.String(length=255), nullable=True, comment='Resumen SEGURO del fallo del último test (sin credenciales).'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Último administrador que modificó la configuración.'),
    sa.CheckConstraint("email_mode in ('environment', 'smtp', 'resend')", name=op.f('ck_system_settings_system_settings_email_mode')),
    sa.CheckConstraint("login_verification_mode in ('disabled', 'code', 'link')", name=op.f('ck_system_settings_system_settings_login_verification_mode')),
    sa.CheckConstraint('agent_lease_ttl_seconds IS NULL OR agent_lease_ttl_seconds > 0', name=op.f('ck_system_settings_system_settings_agent_lease_ttl_positive')),
    sa.CheckConstraint('agent_ticket_ttl_seconds IS NULL OR agent_ticket_ttl_seconds > 0', name=op.f('ck_system_settings_system_settings_agent_ticket_ttl_positive')),
    sa.CheckConstraint('audit_retention_days IS NULL OR audit_retention_days > 0', name=op.f('ck_system_settings_system_settings_audit_retention_positive')),
    sa.CheckConstraint('email_token_minutes IS NULL OR email_token_minutes > 0', name=op.f('ck_system_settings_system_settings_email_token_minutes_positive')),
    sa.CheckConstraint('login_attempts_before_lock IS NULL OR login_attempts_before_lock > 0', name=op.f('ck_system_settings_system_settings_login_attempts_positive')),
    sa.CheckConstraint('notification_retention_days IS NULL OR notification_retention_days > 0', name=op.f('ck_system_settings_system_settings_notification_retention_positive')),
    sa.CheckConstraint('singleton_key = true', name=op.f('ck_system_settings_system_settings_singleton')),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_system_settings_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings')),
    sa.UniqueConstraint('singleton_key', name=op.f('uq_system_settings_singleton_key'))
    )
    op.create_table('user_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False, comment='Proveedor de identidad (google, …).'),
    sa.Column('subject', sa.String(length=255), nullable=False, comment='Identificador ESTABLE del usuario en el proveedor (claim sub).'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Usuario de la plataforma al que pertenece esta identidad.'),
    sa.Column('email_at_link', sa.String(length=255), nullable=True, comment='Correo reportado por el proveedor al momento del vínculo (referencia).'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Momento del vínculo.'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_identities_user_id_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_identities')),
    sa.UniqueConstraint('provider', 'subject', name='uq_user_identities_provider_subject')
    )
    op.create_index('ix_user_identities_user', 'user_identities', ['user_id'], unique=False)
    op.create_table('platform_setup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='Fecha y hora de cierre permanente del Bootstrap HTTP.'),
    sa.Column('completed_by_user_id', sa.UUID(), nullable=True, comment='Usuario inicial que completo el Bootstrap HTTP, si aplica.'),
    sa.Column('system_admin_role_id', sa.UUID(), nullable=True, comment='Rol administrador fundacional protegido por el core.'),
    sa.Column('completion_origin', sa.String(), nullable=True, comment='Origen del cierre: bootstrap de producto o instalacion legacy.'),
    sa.Column('onboarding_dismissed_at', sa.DateTime(), nullable=True, comment='Momento (UTC) en que el administrador descartó el checklist de configuración post-bootstrap (el checklist en sí es DERIVADO del estado real, nunca persiste progreso propio).'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del estado de instalacion.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la ultima modificacion.'),
    sa.CheckConstraint("completion_origin is null or completion_origin in ('bootstrap', 'legacy')", name=op.f('ck_platform_setup_ck_platform_setup_completion_origin')),
    sa.CheckConstraint("status in ('pending', 'completed')", name=op.f('ck_platform_setup_ck_platform_setup_status')),
    sa.CheckConstraint('id = 1', name=op.f('ck_platform_setup_ck_platform_setup_singleton')),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['user.id'], name=op.f('fk_platform_setup_completed_by_user_id_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['system_admin_role_id'], ['role.id'], name=op.f('fk_platform_setup_system_admin_role_id_role'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_setup'))
    )
    op.create_table('role_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('access', sa.String(), nullable=False, comment="Referencia al permiso en código para control de acceso a endpoints (ej: 'users:read', 'roles:write')."),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación del permiso.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última modificación.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que realizó la última modificación.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Desactivación lógica: false inhabilita el permiso sin borrar el registro.'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_role_access_role_id_role'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_role_access_updated_by_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_access')),
    sa.UniqueConstraint('role_id', 'access', name='uq_role_access')
    )
    op.create_index('ix_role_access', 'role_access', ['role_id', 'access'], unique=False)
    op.create_table('user_role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de asignación del rol al usuario.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última modificación.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que realizó la última modificación.'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_user_role_role_id_role'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_user_role_updated_by_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_role_user_id_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_role')),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_index('ix_user_role_role', 'user_role', ['role_id'], unique=False)
    op.create_index('ix_user_role_user', 'user_role', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # --- Siembra de singletons (los servicios exigen que existan) -------------------
    # Política del sistema con defaults seguros; el bootstrap la actualiza después.
    op.execute(
        "INSERT INTO system_settings "
        "(id, singleton_key, public_registration_enabled, login_verification_mode, "
        " password_reset_enabled, analytics_enabled, analytics_require_consent, "
        " analytics_debug_mode, google_login_enabled, email_mode, email_smtp_tls, "
        " email_smtp_ssl) "
        "VALUES (gen_random_uuid(), true, false, 'disabled', true, false, true, "
        "        false, false, 'environment', true, false)"
    )
    # Respaldos DESACTIVADOS y Drive desconectado; el administrador edita en la UI.
    op.execute(
        "INSERT INTO backup_settings "
        "(id, singleton_key, enabled, timezone, daily_time, filename_prefix, "
        " retention_daily_count, retention_monthly_count, retention_yearly_count, "
        " drive_status, explorer_enabled) "
        "VALUES (gen_random_uuid(), true, false, 'UTC', '02:00', 'platform-core', "
        "        7, 12, 5, 'disconnected', false)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_role_user', table_name='user_role')
    op.drop_index('ix_user_role_role', table_name='user_role')
    op.drop_table('user_role')
    op.drop_index('ix_role_access', table_name='role_access')
    op.drop_table('role_access')
    op.drop_table('platform_setup')
    op.drop_index('ix_user_identities_user', table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_table('system_settings')
    op.drop_table('role')
    op.drop_index('ix_push_subscriptions_user', table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index('ix_notifications_push_pending', table_name='notifications')
    op.drop_index('ix_notifications_email_pending', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('backup_settings')
    op.drop_table('backup_oauth_states')
    op.drop_index('ix_audit_events_occurred_at', table_name='audit_events')
    op.drop_index('ix_audit_events_entity', table_name='audit_events')
    op.drop_index('ix_audit_events_actor_user', table_name='audit_events')
    op.drop_index('ix_audit_events_action', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_ai_provider_credentials_user', table_name='ai_provider_credentials')
    op.drop_index('ix_ai_provider_credentials_provider', table_name='ai_provider_credentials')
    op.drop_table('ai_provider_credentials')
    op.drop_table('web_push_credentials')
    op.drop_table('user')
    op.drop_index('ix_backup_runs_status_next_attempt', table_name='backup_runs')
    op.drop_index('ix_backup_runs_status_finished', table_name='backup_runs')
    op.drop_index('ix_backup_runs_drive_file', table_name='backup_runs')
    op.drop_table('backup_runs')
    # ### end Alembic commands ###
