"""initial

Revision ID: ebf33ec14f29
Revises: 
Create Date: 2026-06-25 18:11:20.715576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebf33ec14f29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Desactivación lógica: false elimina al usuario sin borrar el registro.'),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=True, comment='Token de versión del usuario. Cambia al modificar contraseña, email o al forzar cierre de sesiones activas.'),
    sa.Column('locked_until', sa.DateTime(), nullable=True, comment='Fecha hasta la cual la cuenta está bloqueada por intentos fallidos de login.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación del registro.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última modificación.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que realizó la última modificación.'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name='fk_user_updated_by_user', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='pk_user'),
    sa.UniqueConstraint('email', name='uq_user_email')
    )
    op.create_table('role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True, comment='Descripción legible del propósito del rol.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación del registro.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última modificación.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que realizó la última modificación.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Desactivación lógica: false inhabilita el rol y sus permisos asociados sin borrar el registro.'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name='fk_role_updated_by_user', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='pk_role'),
    sa.UniqueConstraint('name', name='uq_role_name')
    )
    op.create_table('role_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('access', sa.String(), nullable=False, comment="Referencia al permiso en código para control de acceso a endpoints (ej: 'users:read', 'roles:write')."),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación del permiso.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última modificación.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que realizó la última modificación.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Desactivación lógica: false inhabilita el permiso sin borrar el registro.'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='fk_role_access_role_id_role', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name='fk_role_access_updated_by_user', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='pk_role_access'),
    sa.UniqueConstraint('role_id', 'access', name='uq_role_access')
    )
    op.create_index('ix_role_access', 'role_access', ['role_id', 'access'], unique=False)
    op.create_table('user_role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de asignación del rol al usuario.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Fecha y hora de la última modificación.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Usuario que realizó la última modificación.'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='fk_user_role_role_id_role', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name='fk_user_role_updated_by_user', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_role_user_id_user', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='pk_user_role'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_index('ix_user_role_role', 'user_role', ['role_id'], unique=False)
    op.create_index('ix_user_role_user', 'user_role', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_role_user', table_name='user_role')
    op.drop_index('ix_user_role_role', table_name='user_role')
    op.drop_table('user_role')
    op.drop_index('ix_role_access', table_name='role_access')
    op.drop_table('role_access')
    op.drop_table('role')
    op.drop_table('user')
    # ### end Alembic commands ###
